@startuml sequence_diagram
actor User
participant FurnitureCompany
participant "FurnitureFactory" as Factory
participant Chair
participant Sofa
participant CoffeeTable

User -> FurnitureCompany: present_furniture(factory)
FurnitureCompany -> Factory: create_chair()
Factory -> Chair: sit_on()
Chair --> Factory: "Sitting on a ... chair"
FurnitureCompany -> Factory: create_sofa()
Factory -> Sofa: lie_on()
Sofa --> Factory: "Lying on a ... sofa"
FurnitureCompany -> Factory: create_coffee_table()
Factory -> CoffeeTable: look_at()
CoffeeTable --> Factory: "Looking at a ... coffee table"
Factory --> FurnitureCompany: Chair, Sofa, CoffeeTable
FurnitureCompany -> User: Display furniture details

@enduml
